### ISSUE TITLE
Can't find the plugin

### ISSUE THREAD

**Issue by pcav** [Kanahiro/qgis-nowcast-tool-plugin#2]
After installation I cannot find an entry for the plugin. Any indication?
Thanks a lot.

**Comment by Kanahiro** [comment]
After installation, ``NowcastTool`` is added in browser like following.
![スクリーンショット 2021-06-14 19 19 24](https://user-images.githubusercontent.com/20744195/121877288-6ec87300-cd45-11eb-8fbb-bb3218408b37.png)

**Comment by pcav** [comment]
thanks for the clarification. It mey be worth the while to add it to the README
